###
### Notes
###
### The travis web interface may choke silently and fail to
### update when there are issues with the .travis.yml file.
###
### The "travis-lint" command-line tool does not catch all
### errors which may lead to silent failure.
###
### Shell-style comments in this file must have "#" as the
### *first* character of the line.
###

###
### language
###

# travis-lint no longer permits this value
language: lisp

###
### defining the build matrix
###
### ===>                                                       <===
### ===> each variation in env/matrix will be built and tested <===
### ===>                                                       <===
###
### variables under env/global are available to the build process
### but don't cause the creation of a separate variation
###

env:
  matrix:
    - RESTAURANT=gtk2
    - RESTAURANT=gtk3
    - RESTAURANT=athena
  global:
    - SOME_TOKEN=some_value

###
### allowing build failures
###

matrix:
  allow_failures:
    - env: RESTAURANT=gtk2
    - env: RESTAURANT=gtk3
    - env: RESTAURANT=athena

###
### limit build attempts to defined branches
###
### notes
###
### This controls which branches are built.
###
### You can also control which branches affect the web badge, by
### appending "?branch=master,staging,production" to the end of the
### image URL (replacing "master,staging,production" with a
### comma-separated list of branches to be reflected in the badge).
###
#
branches:
  only:
    - master
#

###
### runtime initialization
###
### notes
###
### emacs24 (current stable release) is obtained from the
### cassou PPA: http://launchpad.net/~cassou/+archive/emacs
###
### emacs-snapshot (trunk) is obtained from the Ubuntu Emacs Lisp PPA:
### https://launchpad.net/~ubuntu-elisp/+archive/ppa
### For the emacs-snapshot build, bleeding-edge versions
### of all test dependencies are also used.
###

install:
  - sudo apt-get -qq install realpath imagemagick autoconf automake git
  - if [ "$RESTAURANT" = 'gtk2' ]; then
        sudo apt-get -qq install libgtk2.0-dev;
    fi
  - if [ "$RESTAURANT" = 'gtk3' ]; then
        sudo apt-get -qq install libgtk-3-dev;
    fi
  - if [ "$RESTAURANT" = 'athena' ]; then
        sudo apt-get -qq install libxaw7-dev;
    fi

script:
  - autoconf
  - ./configure --with-gui=$RESTAURANT
  - make test
  - make release

###
### settings
###

notifications:
  email: cosmonaut.ok@zoho.com

#
# Emacs
#
# Local Variables:
# indent-tabs-mode: nil
# coding: utf-8
# End:
#
