###
### Notes
###
### The travis web interface may choke silently and fail to
### update when there are issues with the .travis.yml file.
###
### The "travis-lint" command-line tool does not catch all
### errors which may lead to silent failure.
###
### Shell-style comments in this file must have "#" as the
### *first* character of the line.
###

###
### language
###

# travis-lint no longer permits this value
language: lisp

###
### defining the build matrix
###
### ===>                                                       <===
### ===> each variation in env/matrix will be built and tested <===
### ===>                                                       <===
###
### variables under env/global are available to the build process
### but don't cause the creation of a separate variation
###

env:
  matrix:
    - EMACS=restaurant
  global:
    - SOME_TOKEN=some_value

###
### allowing build failures
###

matrix:
  allow_failures:
    - env: EMACS=restaurant

###
### limit build attempts to defined branches
###
### notes
###
### This controls which branches are built.
###
### You can also control which branches affect the web badge, by
### appending "?branch=master,staging,production" to the end of the
### image URL (replacing "master,staging,production" with a
### comma-separated list of branches to be reflected in the badge).
###
#
branches:
  only:
    - master
#

install:
  - sudo apt-get -qq install realpath imagemagick autoconf automake git libgtk2.0-dev libgtk-3-dev libxaw7-dev

script:
  - autoconf
  - ./configure
  - make release
  - autoconf
  - ./configure --with-gui=gtk2
  - make release
  - autoconf
  - ./configure --with-gui=athena
  - make release

###
### settings
###

notifications:
  email: cosmonaut.ok@zoho.com

#
# Emacs
#
# Local Variables:
# indent-tabs-mode: nil
# coding: utf-8
# End:
#
