###
### Notes
###
### The travis web interface may choke silently and fail to
### update when there are issues with the .travis.yml file.
###
### The "travis-lint" command-line tool does not catch all
### errors which may lead to silent failure.
###
### Shell-style comments in this file must have "#" as the
### *first* character of the line.
###

### Check syntax
### https://lint.travis-ci.org/restaurant-ide/restaurant

### https://docs.travis-ci.com/user/customizing-the-build/

###
### language
###

# travis-lint no longer permits this value
language: ruby
os: linux
dist: trusty

cache: bundler

env:
  matrix:
    - RESTAURANT=build
    - RESTAURANT=test
    - RESTAURANT=release
  global:
    - SOME_TOKEN=some_value

###
### allowing build failures
###

matrix:
  allow_failures:
    - env: RESTAURANT=release

###
### limit build attempts to defined branches
###
### notes
###
### This controls which branches are built.
###
### You can also control which branches affect the web badge, by
### appending "?branch=master,staging,production" to the end of the
### image URL (replacing "master,staging,production" with a
### comma-separated list of branches to be reflected in the badge).
###
#
branches:
  only:
    - master
#

###
### runtime initialization
###
### notes
###
### emacs24 (current stable release) is obtained from the
### cassou PPA: http://launchpad.net/~cassou/+archive/emacs
###
### emacs-snapshot (trunk) is obtained from the Ubuntu Emacs Lisp PPA:
### https://launchpad.net/~ubuntu-elisp/+archive/ppa
### For the emacs-snapshot build, bleeding-edge versions
### of all test dependencies are also used.
###

install:
  - sudo apt-get -qq install realpath imagemagick inkscape autoconf automake git libdbus-1-dev xdg-user-dirs curl ruby ruby-bundler markdown ssh-askpass librsvg2-bin
  - bundle install

script:
  - autoconf
  - ./configure --enable-static
  - make el-get
  - make $RESTAURANT
  - if [ $RESTAURANT == "build" ]; then
       /bin/bash -x ./bootstrap.sh && ./restaurant -d --batch;
    fi
  - if [ $RESTAURANT == "release" ]; then
       test -f restaurant-*tar.gz;
    fi

###
### settings
###

notifications:
  email: cosmonaut.ok@zoho.com

#
# Emacs
#
# Local Variables:
# indent-tabs-mode: nil
# coding: utf-8
# End:
#
