source 'https://rubygems.org'

gem 'rubocop', '= 0.41.0'
gem 'pry', '= 0.10.1'
gem 'pry-doc'
gem 'method_source'

gem 'berkshelf', '~> 3.3.1'
gem 'chef', '= 11.16.2'
gem 'knife-solo'
gem 'knife-solo_data_bag'
gem 'foodcritic', '~> 4.0.0'
gem 'test-kitchen'
gem 'chefspec', '~> 4.0.2'
gem 'serverspec', '= 2.0.0'
gem 'addressable', '= 2.3.6'
gem 'gyoku', '= 1.3.1'
gem 'nokogiri', '= 1.5.11'
gem 'akami', '= 1.3.1'
gem 'faraday', '= 0.9.0'
