#!/bin/sh

set -e

ME=$(readlink -f $0)
MYDIR=$(dirname $ME)

if [ ! -z $EMACS ]; then
    :
elif [ -x $MYDIR/emacs/bin/emacs ]; then
    export EMACS=$MYDIR/emacs/bin/emacs
    export EMACSDATA=$MYDIR/emacs/etc/
    export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$MYDIR/emacs/lib/
elif [ ! -z `which emacs` ]; then
    export EMACS=`which emacs`
else
    echo "ERROR: There is no ``emacs`` binary in system"
    exit 1
fi

VERSION=$($EMACS -Q --batch --script ${MYDIR}/rc/version.el --eval '(restaurant-version t)')

# if [ ! -z $1 ] && [ $1 == "devmode" ]; then
#     cd /tmp/
#     $EMACS -Q $MYDIR/rc/*.el &
#     shift
#     OPTIONS="--eval '(setq debug-on-error t)'"
# fi
    
$EMACS -q -l $MYDIR/init.el --name restaurant --title "Restaurant Chef IDE version: (v.${VERSION})" $OPTIONS $@
